name: EBT01 Web Nav

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:

    runs-on: windows-latest

    steps:
    - name: Open File to Checkout.
      run: |
        ./index.html
